name: Next Deploy (PM2)
on:
  workflow_call:
    inputs:
      app_path: { required: true, type: string }   # /srv/apps/my-next
      pm2_name: { required: true, type: string }   # my-next
      node: { type: string, default: '20' }
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: ${{ inputs.node }} }

      # Cài & build trên runner (máy VPS)
      - name: Install deps
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Sync to target folder
        run: |
          sudo mkdir -p "${{ inputs.app_path }}"
          sudo chown -R $USER:$USER "${{ inputs.app_path }}"
          rsync -a --delete --exclude='.git' ./ "${{ inputs.app_path }}"/

      # Prod deps + start/restart PM2
      - name: Start/Restart PM2
        run: |
          cd "${{ inputs.app_path }}"
          # trong runtime chỉ cần deps production
          npm ci --omit=dev
          pm2 start ecosystem.config.js || pm2 restart "${{ inputs.pm2_name }}"
          pm2 save
